### ISSUE TITLE
Failed to activate the heroku-tools package

### ISSUE THREAD

**Issue by sheffy6** [jamesward/atom-heroku-tools#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [heroku-tools](https://github.com/jamesward/atom-heroku-tools) package, v0.3.0
### Stack Trace

Failed to activate the heroku-tools package

```
At Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.Menu.update (/Users/localadmin/.atom/packages/heroku-tools/lib/menu.coffee:10:18)
    at Object.module.exports.HerokuTools.activate (/Users/localadmin/.atom/packages/heroku-tools/lib/heroku.coffee:12:12)
    at Package.module.exports.Package.activateNow (/Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Users/localadmin/.atom/1.8.0/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
formatter-tidy, v1.0.1
heroku-tools, v0.3.0

# Dev
No dev packages
```

**Comment by jamesward** [comment]
Thanks for the bug report!  Version `0.3.1` has been released with a fix.
